name: RepairChest
main: com.webkonsept.bukkit.repairchest.RepairChestPlugin
version: 0.6
website: http://minecraft.webkonsept.com/
author: Fredrik Vold
database: false
description: >
        Provides a way to repair tools
        Cost is done in physical items, by default Gold Ingots
commands:
    repairchest:
        aliases: rc
        description: Replaces all previous /rc*something* commands
        usage: /<command> [reload|test]
permissions:
    repairchest.*:
        description: Full access
        children:
            repairchest.use: true
            repairchest.create: true
            repairchest.destroy: true
            repairchest.command.reload: true
            repairchest.command.test: true
    repairchest.command.*:
        description: Access to both commands
        children:
            repairchest.command.reload: true
            repairchest.command.test: true
    repairchest.command.reload:
        description: Access to /rc reload
        default: op
    repairchest.command.test:
        description: Access to /rc test
        default: op
    repairchest.use:
        description: Using repairchests
        default: op
    repairchest.create:
        description: Creating repairchests
        default: op
    repairchest.destroy:
        description: Destroying repairchests
        default: op